### PR TITLE
ALLIN

### PR DESCRIPTION
**Pull request by shawnim**
ALLIN DAO betting ecosystem by InsideLine Inc.

### CODE REVIEW

**Comment by nahern** [comment]
Hi @shawnim, can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site. Also if you have a blurb explaining your project and/or whitepaper/specification that would be great. Thank you!

**Comment by shawnim** [comment]
Our website URL is https://betallin.io/

The team can be seen on our website by clicking About Us.
We have a global team of 8 led by:
Marc Butterly - CEO
Shawn McMurdo - CTO
Ryan Sweeney - CMO
Nathan Evans - CIO

ALLIN is a community focused betting ecosystem with an easy-to-use all-in-one betting app, ways to earn yield by "being the house", transparent and verifiable games, and an ethical approach to addressing addictive behavior.
all-in-logo

**Comment by nahern** [comment]
many thanks Shawn, also do you have a GitHub repository?

**Comment by shawnim** [comment]
Nothing public while we are working on the prototype.
Shawn

    On Monday, January 10, 2022, 04:43:05 AM PST, Niamh Ahern ***@***.***> wrote:  
 
 


many thanks Shawn, also do you have a GitHub repository?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
