### PR TITLE
Moneyflow

### PR DESCRIPTION
**Pull request by shawnim**
Moneyflow Organization is creating simple personal money management ecosystem built around the Moneyflow app and the Cardano based Moneyflow token.

### CODE REVIEW

**Comment by nahern** [comment]
Hi @shawnim, can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site. Also if you have a blurb explaining your project and/or whitepaper/specification that would be great. Thank you!

**Comment by shawnim** [comment]
Our website URL is https://moneyflow.org/

You can see our team on the website by clicking About.
The team is led by:
Powell Loskamp - CEO
Mike Gough - CFO
Shawn McMurdo - CTO

Moneyflow Organization, Home of the Moneyflow 3-Step Money Management System for individuals, families, and small businesses. Our mission is economic empowerment and happiness for individuals and families. The Moneyflow 3-Step System is a simple, game-like money management system and social support community, that helps our users control their cash flow, build their net worth, and find their economic happiness.
moneyflow-logo-FINAL itshowmoneyworks

**Comment by nahern** [comment]
many thanks Shawn, also do you have a GitHub repository?

**Comment by shawnim** [comment]
Nothing public at this time.Shawn

    On Monday, January 10, 2022, 04:42:52 AM PST, Niamh Ahern ***@***.***> wrote:  
 
 


many thanks Shawn, also do you have a GitHub repository?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
