### PR TITLE
Add Byron Network

### PR DESCRIPTION
**Pull request by alternateved**
Hello,

I would like to add [Byron Network](https://byron.network/) to the list of DEXes and Wallets. If there is anything that needs fixing or if you require additional information, please let me know.

Thanks!

### CODE REVIEW

**Comment by nahern** [comment]
Hi @alternateved can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site please. Also if you have a blurb explaining your project please.

**Comment by alternateved** [comment]
## Description of Byron Network

Byron Network aims to bring the cutting edge solution for traders, hodlers and blockchain lovers. HD Mobile Wallet and a decentralized exchange on Cardano Blockchain is only the first step in the development of the Byron ecosystem. Our goal is to deliver investment tools and a cryptocurrency gateway for multichain investing for any blockchain enthusiast. Great experience with profound UX, thoughtful components and ability to integrate advantageous API is our top priority.

## Team

Our team comprises of experienced developers and knowledgeable crypto experts, passionate about creating the backbone of the crypto trading industry. We have had a 5-year long experience building blockchain projects for our clients as a BinarApps.com software company. We supported projects such as Everest.org, Brave.com, Dash.org, Asdra.com and Minerva. Cardano with its uniqueness is a perfect opportunity for our team to make use of our expertise and contribute to the constantly expanding community. Thanks to the delivery of expectation-exceeding user products we hope to capture the potential behind Cardano Blockchain. Having the years-long yet state-of-the-art experience in the field helped us to understand the market as well as to recognise its need for a release of a cross-chain solution.

Additional information about members of our team can be found at the end of this presentation: https://byron.network/static/byron-network-presentation.pdf

## Links and resources

__Website__: https://byron.network/
__Logo__: https://raw.githubusercontent.com/byron-network/byron-website/main/src/assets/logo_byron.png

**Comment by nahern** [comment]
thank you kindly

**Review by nahern — APPROVED** [review]
approved, thank you for your contribution

**Pull request merged**
