### PR TITLE
Add GOADA Decentralized exchange

### PR DESCRIPTION
**Pull request by andreabravetti**
Add GOADA Decentralized exchange

### CODE REVIEW

**Comment by nahern** [comment]
can you please provide us with the logo, some profiles of the main individuals involved and a URL to the site. Also if you have a blurb explaining your project and/or whitepaper/specification that would be great. Thank you!

**Comment by andreabravetti** [comment]
Url: https://goada.net/dex

Logo: https://goada.net/metadata.logo.png

WP: https://goada.net/GOADA_White_Paper.pdf

Token: https://cardanoscan.io/token/c6e8c5e0074becdec6c4eba85b2dc7e4308df7d3be02ee0c0bf8307d676f6164

Individuals: Andrea Bravetti (it's me) and Stefano (last name omitted) from Italy, we prefer not to add too many personal details at this stage, but we are also available for a KYC if required.

**Comment by andreabravetti** [comment]
White paper is still in draft but latest version 0.21 is almost stable. We just need better pagination and some images in the roadmap, main content is done. Not sure on the mainnet release date, it may be a week before or after the date in current roadmap, so from Saturday 12 to Saturday 26, this month.

**Comment by andreabravetti** [comment]
Latest draft with some better explanation of how our DEX works: https://goada.net/GOADA_White_Paper_v0.22.DRAFT.pdf
The unversioned link was updated to the same version.

**Review by nahern — APPROVED** [review]
approved, thank you for your contribution

**Pull request merged**
