### PR TITLE
Added CardanoCity to NFT project

### PR DESCRIPTION
**Pull request by EyobDejene**
Proposal to add CardanoCity to NFT Platforms and Projects
Platform: https://cardanocity.io/
Twitter: https://twitter.com/CardanoCity

### CODE REVIEW

**Comment by EyobDejene** [comment]
Proposal to add CardanoCity to NFT Platforms and Projects.
Platform: https://cardanocity.io/
Twitter: https://twitter.com/CardanoCity

**Review by nahern — APPROVED** [review]
approved, thank you for your contribution

**Comment by EyobDejene** [comment]
Thanks @nahern, but i don't see it added into the list

**Comment by EyobDejene** [comment]
Thanks!

**Pull request merged**
