### PR TITLE
Add NuFi Wallet and WingRiders DEX

### PR DESCRIPTION
**Pull request by memoriesadrift**

### CODE REVIEW

**Review by peter-gy — APPROVED** [review]

**Comment by nahern** [comment]
Hi @peter-gy , can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site. Also if you have a blurb explaining your project and/or whitepaper/specification that would be great. Thank you!

**Comment by memoriesadrift** [comment]
@nahern I assume these questions are aimed at the projects to be added to the repo. 
Both of the projects are created by [Vacuumlabs](https://vacuumlabs.com/) who are also responsible for [Adalite](https://adalite.io/). Logos are visible on the websites and social media projects of both projects, if you need higher quality or specific dimensions of the logos please reach out to me.  

## NuFi
Website: https://nu.fi/  
Medium: https://nufi-official.medium.com/  
NuFi is a non-custodial crypto wealth management platform for PoS blockchains and digital assets, currently supporting Cardano and Solana. It features a Cardano NFT gallery and is working to integrate the WingRiders DEX into the wallet, with testing live on testnet atm. All information and specifications available on the [NuFi website](https://nu.fi/).

## WingRiders  
Website: https://www.wingriders.com/
Whitepaper: https://assets.wingriders.com/whitepaper.pdf  
Medium: https://medium.com/@wingriderscom  
WingRiders - The DEX on Cardano - is a fully Cardano native and blazing fast AMM DEX that builds on top of the solid foundations of the Cardano network. Our goal is to create a trusted platform that enables users to exchange native Cardano tokens in a truly decentralized fashion with no intermediaries or single points of failure. It is currently operational on Testnet and integrated within the NuFi wallet.

**Comment by nahern** [comment]
thank you

**Review by nahern — APPROVED** [review]
approved, thank you for your contributions

**Pull request merged**
