### PR TITLE
Add Pallas - Rust-native building blocks for the Cardano blockchain ecosystem.

### PR DESCRIPTION
**Pull request by mark-stopka**

### CODE REVIEW

**Comment by nahern** [comment]
Hi, can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site please. Also if you have a blurb explaining your project please.

**Comment by mark-stopka** [comment]
> Hi, can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site please. Also if you have a blurb explaining your project please.

Hello Niamh,
I am afraid we've got nathing that official, we are just bunch of people building Rust tooling around Cardano, and I aggregate those things onto the list, some are build by dcSpark, some by my company, some by Andrew and other community members.

The tools added today, are done by a company (TxPipe) we found just yesterday, they are building an alternative to `db-sync` and `ogmios`, but in Rust...

If we get funded within Project Catalyst as an independent collective, we would like to build an alternative node in Rust, now we're just building things all over the place.

**Comment by nahern** [comment]
thank you for the background Mark and good luck!

**Review by nahern — APPROVED** [review]
approved, thank you for your contributions

**Pull request merged**
