### PR TITLE
adding iagon

### PR DESCRIPTION
**Pull request by kang-chen**

### CODE REVIEW

**Comment by kang-chen** [comment]
Iagon is a shared storage economy.

**Comment by kang-chen** [comment]
Hi @nahern can you review when you have a chance, thanks

**Comment by nahern** [comment]
Hi @kang-chen can you please provide us with your logo, some profiles of the main individuals involved and a URL to your site please. Also if you have a blurb explaining your project please.

**Comment by kang-chen** [comment]
Hi @nahern sure I can, do you want me to email you or just in github is fine?

Below is the info on the project:

Iagon aims to revolutionize the cloud by developing a storage platform and a processing platform where anyone can profit from shared resources. The whole value proposition circles back to the potential of blockchain technology by letting device owners join the storage and processing power grids to create a completely decentralized data cloud and supercomputer.
We also have a signed Agreement of collaboration with Cardano Foundation & participated in Cardano Summit 2021.
Onepager: https://drive.google.com/drive/folders/1IleL6S2GY61stIqXWciMUTYX8n04F_6S
Team members list:
:point_right: You can check team on the website with LinkedIn links - https://iagon.com/about.html
Just to highlight some of them:
- Dr Navjit Dhaliwal, CEO -> https://www.linkedin.com/in/navjit-dhaliwal-a92484b2/
- Dr Elad Harison, Co-Founder -> https://www.linkedin.com/in/elad-harison-phd-7637002/
- Dr Claudio Lima, Co-Founder -> https://www.linkedin.com/in/crlima10/
- Rohit Gupta, Co-Founder -> https://www.linkedin.com/in/rohit-gupta-1440091
- Darren Camas, Advisor -> https://www.linkedin.com/in/dcamas/
Logo: https://drive.google.com/file/d/14qeT3CAuo6T0RcQNCyksyf3jSWbuIMP7/view?usp=sharing
Website: https://iagon.com/

**Comment by nahern** [comment]
thank you kindly for all the details

**Pull request merged**
